### PR TITLE
Contact Page Title: About Me -> Contact

### PR DESCRIPTION
**Pull request by FrogBomb**
I'M DOING A PULL REQUEST :D

### CODE REVIEW

**Comment by NDHF** [comment]
This is a class assignment so I'm not sure I can let you make the change. Thank you for pointing that out, though.

**Comment by FrogBomb** [comment]
THE CHOICE IS YOURS! (btw, by merging the pull request, it will just apply the edit I did. It's basically the same as accepting an edit in google docs)

**Comment by FrogBomb** [comment]
Want to hang out this week?

**Comment by NDHF** [comment]
Yeah, I can do that. Any day but Thursday.

**Pull request merged**
